### ISSUE TITLE
Question about reproducing result

### ISSUE THREAD

**Issue by KCC13** [hwalsuklee/tensorflow-mnist-CVAE#1]
Hello, 

it seems the part "[Conditional Generation : Analogical reasoning with a given image](https://github.com/hwalsuklee/tensorflow-mnist-CVAE#conditional-generation--analogical-reasoning-with-a-given-image)" doesn't tell us how to reproduce the result. So I wonder how do I reproduce this result, any suggestion would be appreciated.

Thank you very much.

**Comment by hwalsuklee** [comment]
Hi,

You are right.

Codes on the part "Conditional Generation : Analogical reasoning with a given image"  are not included in this repository.

But it is very easy to reproduce the results.

1. Train CVAE.
2. Use your handwritten image as input of encoder (please careful to resize image)
3. Find a z-vector corresponding  to input image. For this you have two options.
3-1. Sampling once with mean vector and standard-deviation vector which are output of encoder.
3-2. Just use mean-vector as a z-vector.
4. Get images from decoder. (a z-vector and one-hot vector for desired label are input for decoder)

**Comment by KCC13** [comment]
Thanks for the reply!

I used the same steps few days ago, and it worked well, sorry for the late reply.

Here is my sample code in case anyone needs it:

```
inimg = test_data[0]
inlab = test_labels[0]
ztmp = sess.run((z), feed_dict={x_hat: inimg.reshape((1, 784)), y: inlab.reshape((1, 10)), keep_prob : 1.})
outimgs = sess.run(decoded, feed_dict={z_in: np.array(ztmp.tolist()*10), fack_id_in: np.eye(10), keep_prob: 1.})

plt.figure()
plt.subplot(1, len(outimgs)+2, 1)
plt.imshow(inimg.reshape(28, 28), cmap = plt.cm.gray)
plt.axis('off')
for i, outimg in enumerate(outimgs):
    plt.subplot(1, len(outimgs)+2, i+3)
    plt.imshow(outimg.reshape(28, 28), cmap = plt.cm.gray)
    plt.axis('off')
plt.show()
```

All the best,
KCC
